// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5QAqJ8DKKCXasSDBrzeAfgE2KrGrksG4',
    appId: '1:299440538112:web:775ea1b60b1a8222358ee5',
    messagingSenderId: '299440538112',
    projectId: 'virtual-herbal-garden-84939',
    authDomain: 'virtual-herbal-garden-84939.firebaseapp.com',
    storageBucket: 'virtual-herbal-garden-84939.firebasestorage.app',
    measurementId: 'G-QYD1MNMDPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWkHBKmc2vFv7hQK2uaIgbgEdFMBnYYEQ',
    appId: '1:299440538112:android:3e3124f1a0cff5cd358ee5',
    messagingSenderId: '299440538112',
    projectId: 'virtual-herbal-garden-84939',
    storageBucket: 'virtual-herbal-garden-84939.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ZM3csWgK06HCeODE-kpy4T_tUNfCCOc',
    appId: '1:299440538112:ios:f3c05949f3f1b19d358ee5',
    messagingSenderId: '299440538112',
    projectId: 'virtual-herbal-garden-84939',
    storageBucket: 'virtual-herbal-garden-84939.firebasestorage.app',
    iosBundleId: 'com.example.virtualHerbalGarden',
  );
}
